version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: buspark_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bus_park
    ports:
      - "5432:5432"
    volumes:
      - buspark_data:/var/lib/postgresql/data

volumes:
  buspark_data:
